## Pair Programming Numpy

**Creación y Indexación:**

1. Crea un array 1D con 50 valores aleatorio del 10 al 99. Accede a los elementos en las posiciones múltiplos de 5.

In [9]:
import numpy as np

array1 = np.random.randint(10, 99, size=50)

print(array1)

print(f"Los elementos en las posiciones multiplos de 5 del array son: {array1[::5]}")

[47 72 33 71 15 34 93 64 83 33 22 16 46 13 38 65 65 21 97 79 25 46 11 87
 52 21 23 74 38 37 59 53 71 76 50 91 25 89 95 70 89 97 79 83 69 36 85 54
 68 27]
Los elementos en las posiciones multiplos de 5 del array son: [47 34 22 65 25 21 59 91 89 36]


2. Crea un array 1D con 30 valores del 1 al 20 (ambos incluidos). Utiliza indexación para obtener los elementos en las posiciones impares.

In [10]:
array2 = np.random.randint(1, 21, size=30)

print(array2)

print(f"Los elementos en las posiciones impares son: {array2[1::2]}")

[16  7  3 18 14  7 17 15 20  1 19 15  8  9  5  4 15  7  3 13 18 16  2  7
  4  4  7  5 12  2]
Los elementos en las posiciones impares son: [ 7 18  7 15  1 15  9  4  7 13 16  7  4  5  2]


3. Crea un array 2D de forma (4, 6) con números aleatorios decimales (no deben estar comprendidos solo entre 0 y 1). Accede a la última fila de la matriz. Los decimales deben estar redondeados a 2 decimales.

In [15]:
array3 = np.random.random_sample((4,6))

array3_redondeado = np.round(array3, 2)

print(array3_redondeado)

array3_redondeado[3]

[[0.87 0.69 0.67 0.77 0.89 0.81]
 [0.33 0.08 0.37 0.18 0.71 0.75]
 [0.45 0.19 0.13 0.86 0.92 0.97]
 [0.27 0.74 0.87 0.57 0.27 0.82]]


array([0.27, 0.74, 0.87, 0.57, 0.27, 0.82])

4. **BONUS:** Crea un array 3D de forma (2, 3, 5) y 30 elementos con números enteros entre 0 y 100 (ambos incluidos). Reemplaza los elementos en posiciones múltiplos de 3 por 0.

In [12]:
import numpy as np

array4 = np.random.randint(0, 101, (2, 3, 5))

print(f"El array que vamos a utilizar es: \n{array4}\n")

array4_flat = array4.flatten()
array4_flat[::3] = 0
array4 = array4_flat.reshape(2, 3, 5)

print(f"El nuevo array es: \n{array4}")

El array que vamos a utilizar es: 
[[[10 86 25 42 81]
  [26 74 25 61 95]
  [36 59 21  2 62]]

 [[57 64 50 69 18]
  [96 61 60 47 10]
  [18 35 31 73 22]]]

El nuevo array es: 
[[[ 0 86 25  0 81]
  [26  0 25 61  0]
  [36 59  0  2 62]]

 [[ 0 64 50  0 18]
  [96  0 60 47  0]
  [18 35  0 73 22]]]


**Reshape y Transpose:**

##### Ejercicios con reshape:

1. Crea un array 3D de forma (2, 3, 4) con valores aleatorios entre 1 y 100 (ambos inclusive). Utiliza reshape para convertirlo en un array 2D. Deberás pensar en la forma que es correcta para hacer este cambio.

In [24]:
array5 = np.random.randint(1, 101, (2, 3, 4))

print(f"{array5}\n")

array_cambiado = np.reshape(array5, (4, 6))

print(array_cambiado)

[[[72 85 22 69]
  [53 26 61 11]
  [98 86 46  9]]

 [[15 98  8 49]
  [84 78 29 51]
  [92 82 73 76]]]

[[72 85 22 69 53 26]
 [61 11 98 86 46  9]
 [15 98  8 49 84 78]
 [29 51 92 82 73 76]]


2. Crea un array 3D de forma (3, 4, 5) con valores enteros del 1 al 61 (sin incluir). Utiliza reshape para convertirlo en un array 2D.

In [26]:
array6 = np.random.randint(1, 61, (3, 4, 5))

print(f"{array6}\n")

array_cambiado = np.reshape(array6, (6, 10))

print(array_cambiado)

[[[47 22  6 27  7]
  [12 22 29 33 44]
  [41 55 37 60  8]
  [37  7 58  3 33]]

 [[25 58  5 12 45]
  [50 46 21 35 22]
  [10 57 18 52 17]
  [24 17 18 32 40]]

 [[13 47 28 41 46]
  [45 38 59  9 14]
  [40 38 14 50 15]
  [54  8 50 44 27]]]

[[47 22  6 27  7 12 22 29 33 44]
 [41 55 37 60  8 37  7 58  3 33]
 [25 58  5 12 45 50 46 21 35 22]
 [10 57 18 52 17 24 17 18 32 40]
 [13 47 28 41 46 45 38 59  9 14]
 [40 38 14 50 15 54  8 50 44 27]]


##### Ejercicios con transpose:

3. Utiliza el array 3D del ejercicio 2 de reshape. Utiliza transpose para permutar los ejes y obtener un nuevo array con forma (5, 4, 3).

In [40]:
print(f"El array con el que vamos a trabajar es: \n{array6}\n")

nuevo_array = np.transpose(array6, axes=(2, 1, 0))

print(f"El nuevo array transpuesto con forma (5, 4, 3) es: \n{nuevo_array}")

El array con el que vamos a trabajar es: 
[[[47 22  6 27  7]
  [12 22 29 33 44]
  [41 55 37 60  8]
  [37  7 58  3 33]]

 [[25 58  5 12 45]
  [50 46 21 35 22]
  [10 57 18 52 17]
  [24 17 18 32 40]]

 [[13 47 28 41 46]
  [45 38 59  9 14]
  [40 38 14 50 15]
  [54  8 50 44 27]]]

El nuevo array transpuesto con forma (5, 4, 3) es: 
[[[47 25 13]
  [12 50 45]
  [41 10 40]
  [37 24 54]]

 [[22 58 47]
  [22 46 38]
  [55 57 38]
  [ 7 17  8]]

 [[ 6  5 28]
  [29 21 59]
  [37 18 14]
  [58 18 50]]

 [[27 12 41]
  [33 35  9]
  [60 52 50]
  [ 3 32 44]]

 [[ 7 45 46]
  [44 22 14]
  [ 8 17 15]
  [33 40 27]]]


4. Utiliza el array 3D del ejercicio 2 de reshape. Utiliza transpose para cambiar el orden de los ejes y obtener un nuevo array con forma (3, 5, 4).

In [42]:
print(f"El array con el que vamos a trabajar es: \n{array6}\n")

nuevo_array = np.transpose(array6, axes=(0, 2, 1))

print(f"El nuevo array transpuesto con forma (3, 5, 4) es: \n{nuevo_array}")

El array con el que vamos a trabajar es: 
[[[47 22  6 27  7]
  [12 22 29 33 44]
  [41 55 37 60  8]
  [37  7 58  3 33]]

 [[25 58  5 12 45]
  [50 46 21 35 22]
  [10 57 18 52 17]
  [24 17 18 32 40]]

 [[13 47 28 41 46]
  [45 38 59  9 14]
  [40 38 14 50 15]
  [54  8 50 44 27]]]

El nuevo array transpuesto con forma (3, 5, 4) es: 
[[[47 12 41 37]
  [22 22 55  7]
  [ 6 29 37 58]
  [27 33 60  3]
  [ 7 44  8 33]]

 [[25 50 10 24]
  [58 46 57 17]
  [ 5 21 18 18]
  [12 35 52 32]
  [45 22 17 40]]

 [[13 45 40 54]
  [47 38 38  8]
  [28 59 14 50]
  [41  9 50 44]
  [46 14 15 27]]]


##### Preguntas teóricas:

5. ¿Qué diferencia existe entre el reshape y el transpose?

`np.transpose()`: Es una función de la biblioteca NumPy que se utiliza para intercambiar las dimensiones de un *array*. Toma como argumento un *array* y devuelve un nuevo *array* con las dimensiones intercambiadas.

`np.reshape()`: Es una función de NumPy que se utiliza para cambiar la forma de un *array* sin cambiar sus datos subyacentes. Permite reorganizar los elementos de un *array* en una nueva forma especificada por el usuario.

6. ¿Y entre el transpose y el swapaxes?

`np.transpose()`: Es una función de la biblioteca NumPy que se utiliza para intercambiar las dimensiones de un *array*. Toma como argumento un *array* y devuelve un nuevo *array* con las dimensiones intercambiadas.

`np.swapaxes()`: Es un método de Numpy que se utiliza para intercambiar dos ejes (dimensiones) específicos de un *array*. Permite reorganizar los ejes de un *array* sin cambiar los datos subyacentes.

**Funciones Aritméticas y Estadísticas:**

1. Crea un array de tres 3D con elementos entre el 0 y 1 de forma (2, 3, 5) cuyos valores solo tengan 1 decimal.

In [27]:
array7 = np.random.rand(2, 3, 5)

array_redondeado = np.round(array7, 1)

print(f"{array_redondeado}")

[[[0.3 0.7 0.  0.1 0.7]
  [0.9 0.7 0.1 0.  0.3]
  [0.2 0.7 0.1 0.4 0.3]]

 [[0.7 0.5 0.5 0.5 0.5]
  [0.4 0.3 0.9 0.1 0.6]
  [0.9 0.7 0.7 0.3 0.3]]]


2. Crea un array vacío con la misma forma y dimensiones que el array creado anteriormente. Vamos a reemplazar los valores de la matriz vacía que nos acabamos de crear pero basándonos en los valores del primer array bajo las siguientes condiciones:

- Si el valor del array es igual que la media, se reemplaza por "A".

- Si el valor del array es mayor que la media, se reemplaza por "B".

- Si el valor del array es menor que la media, se reemplaza por "C".

- Si el valor es igual que el máximo, se reemplaza por "D".

- Si el valor es igual que el mínimo, se reemplaza por "E".

In [44]:
import numpy as np

media = np.mean(array7)
maximo = np.max(array7)
minimo = np.min(array7)

print("La media es:", media)
print("El valor maximo es:", maximo)
print("El valor minimo es:", minimo)

print("----------------------------------------")

array8 = np.where(array7 == maximo, "D",
         np.where(array7 == minimo, "E",
         np.where(array7 > media, "B",
         np.where(array7 < media, "C",
         np.where(array7 == media, "A", "")))))

print(f"El nuevo array es:\n", array8)

La media es: 0.44157775088371365
El valor maximo es: 0.9326382035796769
El valor minimo es: 0.025227196097870497
----------------------------------------
El nuevo array es:
 [[['C' 'B' 'E' 'C' 'B']
  ['D' 'B' 'C' 'C' 'C']
  ['C' 'B' 'C' 'C' 'C']]

 [['B' 'B' 'B' 'B' 'B']
  ['C' 'C' 'B' 'C' 'B']
  ['B' 'B' 'B' 'C' 'C']]]
